cmake_minimum_required(VERSION 3.16)
project(shark)

enable_testing()

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()

set(CMAKE_CXX_FLAGS_DEBUG "-g")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-write-strings -Wno-unused-result -maes -Wno-ignored-attributes -march=native -Wno-deprecated-declarations")

find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

find_package (Eigen3 REQUIRED NO_MODULE)

add_subdirectory(ext/cryptoTools)
add_subdirectory(ext/cnpy)

add_library(${PROJECT_NAME}
    src/utils/timer.cpp
    src/utils/comm.cpp
    src/utils/lookuptable.cpp
    src/protocols/common.cpp
    src/protocols/init.cpp
    src/protocols/finalize.cpp
    src/protocols/input.cpp
    src/protocols/output.cpp
    src/protocols/matmul.cpp
    src/protocols/drelu.cpp
    src/protocols/b2a.cpp
    src/protocols/select.cpp
    src/protocols/relu.cpp
    src/protocols/conv.cpp
    src/protocols/maxpool.cpp
    src/protocols/sumpool.cpp
    src/protocols/mul.cpp
    src/protocols/lut.cpp
    src/protocols/truncate.cpp
    src/protocols/down.cpp
    src/protocols/up.cpp
    src/protocols/matmulpar.cpp
    src/crypto/dcfbit.cpp
    src/crypto/dcfring.cpp
    src/crypto/dpfring.cpp
)

target_link_libraries (${PROJECT_NAME} Eigen3::Eigen cryptoTools)
target_include_directories(${PROJECT_NAME}
PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
)

# list of all single running tests
set(SINGLE_TESTS
    dcfbit
    dcfring
    dpfring
    span
    truncate-clear
)

# run for all single running tests
foreach(testname IN LISTS SINGLE_TESTS)
    add_executable(test-single-${testname} tests/single/${testname}.cpp)
    target_link_libraries(test-single-${testname} ${PROJECT_NAME})
    add_test(NAME test-single-${testname} COMMAND test-single-${testname})
endforeach()

set(MULTI_TESTS
    init
    matmul
    select
    drelu
    relu
    truncate
    down
    up
    inv
    gelu
    nexp
    rsqrt
    softmax
    matmul-big
)

foreach(testname IN LISTS MULTI_TESTS)
    add_executable(test-multi-${testname} tests/multi/${testname}.cpp)
    target_link_libraries(test-multi-${testname} ${PROJECT_NAME})
    add_test(NAME test-multi-${testname} COMMAND bash ${CMAKE_CURRENT_SOURCE_DIR}/tests/run-multi.sh multi-${testname})
endforeach()

set (BENCHMARKS
    bert
    gpt2
)

foreach (benchmark IN LISTS BENCHMARKS)
    add_executable(benchmark-${benchmark} benchmarks/${benchmark}.cpp)
    target_link_libraries(benchmark-${benchmark} ${PROJECT_NAME})
endforeach()

add_executable(benchmark-bert-acc benchmarks/bert_acc.cpp)
target_link_libraries(benchmark-bert-acc ${PROJECT_NAME} cnpy)
